require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Fit4yoursport' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNWalkCounter', :path => '../node_modules/react-native-walk-counter/ios'

  pod 'RCTYouTube', :path => '../node_modules/react-native-youtube'

  # add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  # pod 'react-native-pedometer', :path => '../node_modules/react-native-pedometer-ios-android'

  # pod 'react-native-universal-pedometer', :path => '../node_modules/@t2tx/react-native-universal-pedometer'

  # pod 'react-native-agora', :path => '../node_modules/react-native-agora'

  pod 'react-native-jitsi-meet', :path => '../node_modules/react-native-jitsi-meet'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  # pod 'RNWalkCounter', :path => '../node_modules/react-native-walk-counter'

  pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'

  target 'Fit4yoursportTests' do
    inherit! :complete
    # Pods for testing
  end

  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'Fit4yoursport-tvOS' do
  # Pods for Fit4yoursport-tvOS

  target 'Fit4yoursport-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
